(ns ^{:author "Daniel Leong"
      :doc "Take a rendered ATIS object and build the text
            used to create a voice ATIS"}
  xatis.abbr
  (:require [clojure.string :as s]))

;; from vatis
(def abbreviations
  (->>
    ["ACFT" "AIRCRAFT" "LGT" "LIGHT"
     "ADVS" "ADVISE" "LGTD" "LIGHTED"
     "ADVSD" "ADVISED" "LGTS" "LIGHTS"
     "ADVZY" "ADVISORY" "LLWS" "LOW LEVEL WIND SHEAR"
     "ADVZYS" "ADVISORIES" "LLZ" "LOCALIZER"
     "ALS" "APPROACH LIGHTING SYSTEM" "LOC" "LOCALIZER"
     "ALT" "ALTITUDE" "MOD" "MODERATE"
     "ALTS" "ALTITUDES" "MULTI" "MULTIPLE"
     "APCH" "APPROACH" "NA" "NOT AUTHORIZED"
     "APCHS" "APPROACHES" "NOTAM" "NOTICE TO AIRMEN:"
     "APP" "APPROACH" "NOTAMS" "NOTICES TO AIRMEN:"
     "APPR" "APPROACH" "OPER" "OPERATE"
     "APPRS" "APPROACHES" "OPS" "OPERATIONS"
     "APPS" "APPROACHES" "OTS" "OUT OF SERVICE"
     "ARPT" "AIRPORT" "OUBD" "OUTBOUND"
     "ARR" "ARRIVAL" "PIREP" "PILOT WEATHER REPORT"
     "ARRS" "ARRIVALS" "PROC" "PROCEDURE"
     "ATTN" "ATTENTION" "PROG" "PROGRESS"
     "AUTH" "AUTHORIZED" "RMNG" "REMAINING"
     "AVBL" "AVAILABLE" "RMVL" "REMOVAL"
     "BA" "BRAKING ACTION" "RQST" "REQUEST"
     "BAA" "BRAKING ACTION ADVISORIES" "RQSTD" "REQUESTED"
     "BC" "BACKCOURSE" "RWY" "RUNWAY"
     "BTWN" "BETWEEN" "RWYS" "RUNWAYS"
     "CAUT" "CAUTION" "SIMUL" "SIMULTANEOUS"
     "CLNC" "CLEARANCE" "SVC" "SERVICE"
     "CLR" "CLEAR" "SVCS" "SERVICES"
     "CLRD" "CLEARED" "SVR" "SEVERE"
     "CLSD" "CLOSED" "TFC" "TRAFFIC"
     "CMSN" "COMMISSION" "TFR" "TEMPORARY FLIGHT RESTRICTION"
     "CMSND" "COMMISSIONED" "TURB" "TURBULENCE"
     "CTC" "CONTACT" "TWY" "TAXIWAY"
     "CTL" "CONTROL" "TWYS" "TAXIWAYS"
     "CTLD" "CONTROLLED" "US" "UNSERVICEABLE"
     "DCMSN" "DECOMMISSION" "UNCTLD" "UNCONTROLLED"
     "DCMSND" "DECOMMISSIONED" "UNUSBL" "UNUSABLE"
     "DEP" "DEPARTURE" "USBL" "USABLE"
     "DEPS" "DEPARTURES" "VFY" "VERIFY"
     "DEPTG" "DEPARTING" "VCTR" "VECTOR"
     "DIST" "DISTANCE" "VCTRS" "VECTORS"
     "DRCTN" "DIRECTION" "VIS" "VISUAL"
     "DURG" "DURING" "XPDR" "TRANSPONDER"
     "DURN" "DURATION" "XPDRS" "TRANSPONDERS"
     "EFCT" "EFFECT" "XPNDR" "TRANSPONDER"
     "EFF" "EFFECTIVE" "XPNDRS" "TRANSPONDERS"
     "EQPT" "EQUIPMENT" "XTM" "EXTREME"
     "EXPT" "EXPECT" "N" "NORTH"
     "FLT" "FLIGHT" "NNE" "NORTH NORTHEAST"
     "FREQ" "FREQUENCY" "NE" "NORTHEAST"
     "FT" "FEET" "ENE" "EAST NORTHEAST"
     "GND" "GROUND" "E" "EAST"
     "GS" "GLIDESLOPE" "ESE" "EAST SOUTHEAST"
     "HDG" "HEADING" "SE" "SOUTHEAST"
     "HDGS" "HEADINGS" "SSE" "SOUTH SOUTHEAST"
     "HELI" "HELICOPTER" "S" "SOUTH"
     "HS" "HOLD SHORT" "SSW" "SOUTH SOUTHWEST"
     "HAZ WX INFO" "HAZARDOUS WEATHER INFORMATION" "SW" "SOUTHWEST"
     "INBD" "INBOUND" "WSW" "WEST SOUTHWEST"
     "INTXN" "INTERSECTION" "W" "WEST"
     "INVOF" "IN VICINITY OF" "WNW" "WEST NORTHWEST"
     "LAHSO" "LAND AND HOLD SHORT OPERATIONS" "NW" "NORTHWEST"
     "LDG" "LANDING" "NNW" "NORTH NORTHWEST"
     "NRN" "NORTHERN" "SRN" "SOUTHERN"
     "ERN" "EASTERN" "WRN" "WESTERN"
     "NWRN" "NORTHWESTERN" "SWRN" "SOUTHWESTERN"
     "NERN" "NORTHEASTERN" "SERN" "SOUTHEASTERN"
     "PRM" "PRECISION RUNWAY MONITOR" "PAPI" "PRECISION APPROACH PATH INDICATOR"
     "VASI" "VISUAL APPROACH SLOPE INDICATOR" "OAT" "OUTSIDE AIR TEMPERATURE"]
    (partition 2)
    (map 
      (fn [[k v]]
        [(re-pattern (str "\\b" k "\\b")) v]))))

(defn expand-abbrs
  [input]
  (loop [output input
         abbrs abbreviations]
    (if-let [[k v] (first abbrs)]
      (recur (s/replace output k v) (rest abbrs))
      output)))
